### ISSUE TITLE
Cannot input "R" or backspace key while settings checklist's tag

### ISSUE THREAD

**Issue by stephane-dereppe** [kullervo16/checklist#119]
While setting the tag for a new checklist, we cannot enter the "R" character neither use the "backspace" key.

![image](https://user-images.githubusercontent.com/3494830/26867579-2f4e5934-4b66-11e7-8c1d-03d2bdcfd6ad.png)

**Comment by kullervo16** [comment]
Apparently the ng-enter directive to catch the enter has some side effects... for some reason, backspace and r/R are coming in differently... added some logic to the intercepter to apply both strange functions + added a test for all alfanumeric tag values. Also prevent /, since this messes up the URL structure (the / is accepted but eaten by the script before sending it to the backend)
