### ISSUE TITLE
No tag managment screen

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#28]
There no screen to manage tags.  There is no way to change Acc tags to ACC tags for every checklists.  We have to do it manually for now.

**Comment by kullervo16** [comment]
Added the possibility to delete a tag in all checklists, rename it to a new value or merge it into an existing value...

**Comment by kernixski** [comment]
Tags coming from the template are protected when we try to delete it (the user is not able to delete a tag if this tag is defined in the template or if the tag has been generated based on the directory name or the template name).  But the tag management screen bypass this protection.  Is this the expected behavior ?

**Comment by kullervo16** [comment]
Well, the template tag protection is in checklist only, where you normally have a view on a single checklist, you're not concerned with the overall tagging structure of your project

In the tag management screen you do have the view on all tags... if you decide there to delete/rename/merge a template tag, I think we should honor that... so yes, this was intentional.

**Comment by kernixski** [comment]
It depends how you see your objects.  In my point of view, we have checklists and checklists have tags.  Checklists have rules.  One rule is that we cannot delete the tag with the directory name.  Another rule is that we cannot delete the tag with the template name.  

The tag management screen manage the tags of the checklists and should follow the checklists rules. 

The rules have been added to prevent the user to make "errors".  Then I prefer to keep the rules everywhere in the application.

But it is my own point of view.  You decide. ;-)

BTW, we should maybe hide this screen in the menu to prevent regular users to access it and to delete tags by mistake.

**Comment by kullervo16** [comment]
Restricted tag management screen to the admin role (it is visible for all with the listing and the stats, but the edit button/action is restricted).

Also used the logic of #89 to prevent deleting the tag when it originated from a template.

Added some migration code to initialize the originalTemplateTags to the (current) tags of the template so that also the old ones get the tags from the ID (and the tag management screen protection works)
