### ISSUE TITLE
We should not be able to create a new checklist if the tag list is not unique

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#29]

**Comment by kullervo16** [comment]
Unable to create is a bit difficult, since you create them from the template before the tags are assigned. However, I can disallow you to start using the checklist until the combination is unique...

Also refactor the add tag system... the add button at the bottom of the screen is different to the other tasks where we use modal dialogs... Also, not that logical that the tags are on the top and the add button is at the bottom... so added a + icon to add a tag, and put a modal dialog.. the modal will only disappear when the combination of the tags is unique.

**Comment by kullervo16** [comment]
Also took care of when you delete a tag that would make it non-unique...
