### ISSUE TITLE
Reopen button is visible on all steps

### ISSUE THREAD

**Issue by kullervo16** [kullervo16/checklist#83]
#32 asked for only showing the reopen button on the last executed step... now the reopen button is visible on all executed steps...

**Comment by kernixski** [comment]
It is the expected behavior.

Explanation: if you want a step depend on another step, add a condition on this step (with or without option value). If a step depends on one step and the step is started, then the step this step depends on will not be reopenable. But if not, it means that nothing depends on this step and there is no reason this step can not be reopened. 

Make a try. ;-)

**Comment by kernixski** [comment]
If you want, we can add a `autocrate_conditions` boolean with default value to `true` to make each step depending on the previous step, but we first have to make multiple conditions possible because current templates already use conditions.

**Comment by kullervo16** [comment]
not needed, just wanted to make sure... current behaviour is ok
